# Generated by Django 5.0.3 on 2024-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_img/'),
            preserve_default=False,
        ),
    ]
