# Generated by Django 4.2.9 on 2024-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_info_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('black', 'black'), ('white', 'white'), ('green', 'green'), ('violet', 'violet'), ('turquoise', 'turquoise'), ('khaki', 'khaki'), ('grey', 'grey'), ('petrol', 'petrol'), ('blue', 'blue'), ('lightblue', 'lightblue'), ('olive', 'olive')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('L', 'L'), ('M', 'M'), ('XL', 'XL')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
